### ISSUE TITLE
systemd service file hard codes _cscreen for User/Group

### ISSUE THREAD

**Issue by ismail** [openSUSE/cscreen#1]
cscreend.service has:

```
[Service]
User=_cscreen
Group=_cscreen
```

But this breaks when someone sets a `SCREEN_OWNER` in `/etc/sysconfig/cscreen` . When `SCREEN_OWNER` is set to a custom value, it should be used for `User/Group` instead.

**Comment by olafhering** [comment]
Since this is part of the rpm package, the user/group name is hardly a configurable component anymore.

**Comment by ismail** [comment]
> Since this is part of the rpm package, the user/group name is hardly a configurable component anymore.

Then, SCREEN_OWNER should be removed as not to confuse the user.

**Comment by olafhering** [comment]
A `*.service` file can be configured: `Along with a unit file foo.service, a "drop-in" directory foo.service.d/ may exist.`.

Is there actually a use case for `SCREEN_OWNER`? The enforced user `_cscreen` is always present because it is created in `%pre`.

**Comment by ismail** [comment]
> A `*.service` file can be configured: `Along with a unit file foo.service, a "drop-in" directory foo.service.d/ may exist.`.
> 
> Is there actually a use case for `SCREEN_OWNER`? The enforced user `_cscreen` is always present because it is created in `%pre`.

Some of our cscreen config needs root permissions to run, that was the initial problem for us.

**Comment by olafhering** [comment]
Does the mentioned `cscreen.service.d` solve this usecase?

**Comment by ismail** [comment]
SCREEN_OWNER is still to be removed imho.

**Comment by olafhering** [comment]
After poking around in the code it appears that one should be able to change the owner, to `root` for example. And the code appears to handle it. Just `cscreen.service` needs the extra change because `User=` does not consume variables AFAICS.
