### ISSUE TITLE
Moving cscreenrc_allow_update probably introduced security issue

### ISSUE THREAD

**Issue by cboltz** [openSUSE/cscreen#3]
In https://github.com/openSUSE/cscreen/pull/2 you moved `cscreenrc_allow_update` from a directory that is only writeable for root (`/etc/`) to a world-writeable directory (`/dev/shm/`), which introduces the "usual" security risks of hardcoded filenames in world writeable directories, for example symlink attacks.

Unless you are very sure that there is absolutely no risk (which would surprise me), I'd recommend to use a directory that is only writeable by root, for example `/run/`.

**Comment by olafhering** [comment]
There is no risk. `cscreen` is just the consumer of the path. Storing it in tmpfs makes sure no stale lock is left behind after an unexpected crash.
